### ISSUE TITLE
Question mark (?) in local file name can cause upload to fail

### ISSUE THREAD

**Issue by stuart-mclaren** [Azure/azure-batch-samples#105]
If the local file has a question mark in its name the upload can stack trace:

$ blobxfer --version
0.9.9.8

$ mkdir x

$ echo x > 'x/xxx?.xxx'

$ blobxfer  --storageaccountkey 'redacted' redacted container x
Traceback (most recent call last):
  File "/redacted/local/lib/python2.7/site-packages/blobxfer.py", line 877, in run
    offset, bytestoxfer, encparam, flock, filedesc)
  File "/redacted/local/lib/python2.7/site-packages/blobxfer.py", line 1002, in putblobdata
    content_md5=contentmd5, timeout=self.timeout)
  File "/redacted/local/lib/python2.7/site-packages/blobxfer.py", line 1309, in azure_request
    return req(*args, **kwargs)
  File "/redacted/local/lib/python2.7/site-packages/azure/storage/blob/blobservice.py", line 2366, in put_block
    self._perform_request(request)
  File "/redacted/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 178, in _perform_request
    _storage_error_handler(ex)
  File "/redacted/local/lib/python2.7/site-packages/azure/storage/_serialization.py", line 25, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/redacted/local/lib/python2.7/site-packages/azure/storage/_common_error.py", line 82, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
AzureHttpError: An HTTP header that's mandatory for this request is not specified.
<?xml version="1.0" encoding="utf-8"?><Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that's mandatory for this request is not specified.
RequestId:redacted
Time:2016-01-24T17:47:06.9200167Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>

Removing the '?' makes the upload succeed.

**Comment by alfpark** [comment]
This is a known issue with the Azure Python Storage SDK: https://github.com/Azure/azure-storage-python/issues/67

A fix for properly handling file/blob names containing '?' is forthcoming in the next release if SAS keys are used.

**Comment by stuart-mclaren** [comment]
Hi,

I still see the same behaviour with my reproducer:

$ blobxfer --version
0.9.9.9

$ blobxfer --storageaccountkey 'redacted' redacted container x
xfer progress: [                              ] 0.00%       0.00 blocks/min    Traceback (most recent call last):
  File "/blobxfer2/local/lib/python2.7/site-packages/blobxfer.py", line 880, in run 
    offset, bytestoxfer, encparam, flock, filedesc)
  File "/blobxfer2/local/lib/python2.7/site-packages/blobxfer.py", line 1002, in putblobdata 
    content_md5=contentmd5, timeout=self.timeout)
  File "/blobxfer2/local/lib/python2.7/site-packages/blobxfer.py", line 1309, in azure_request
    return req(*args, **kwargs)
  File "/blobxfer2/local/lib/python2.7/site-packages/azure/storage/blob/blobservice.py", line 2366, in put_block
    self._perform_request(request)
  File "/blobxfer2/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 178, in _perform_request
    _storage_error_handler(ex)
  File "/blobxfer2/local/lib/python2.7/site-packages/azure/storage/_serialization.py", line 25, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/blobxfer2/local/lib/python2.7/site-packages/azure/storage/_common_error.py", line 82, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
AzureHttpError: An HTTP header that's mandatory for this request is not specified.
<?xml version="1.0" encoding="utf-8"?><Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that's mandatory for this request is not specified.
RequestId:6bd0ee85-0001-004c-4794-5bb3af000000
Time:2016-01-30T19:30:14.1340017Z</Message><HeaderName>x-ms-blob-type</HeaderName></Error>

Is the stack trace when storageaccountkey is used something it's possible to fix?

For example, if a storage account key is provided could a sas key be generated from it as needed?

If not, what is the recommended way for blobxfer users to generate sas keys?

Thanks.

**Comment by alfpark** [comment]
As noted above, this is an underlying issue with the Azure Python Storage SDK if using a storage account key. You can generate a SAS key separately from the blobxfer invocation using the Azure Python Storage SDK or various graphical tools.
