### ISSUE TITLE
Unable to upload to China BLOB

### ISSUE THREAD

**Issue by bosborne-movideo** [Azure/azure-batch-samples#16]
There seems to be an issue when using the blobep switch. Running like this

blobxfer.py --storageaccountkey <KEY> test storage file.mp4 --upload --blobep blob.core.chinacloudapi.cn

Throws this error

Traceback (most recent call last):
  File "./blobxfer.py", line 1310, in <module>
    main()
  File "./blobxfer.py", line 980, in main
    blobskipdict = get_blob_listing(blob_service, args)
  File "./blobxfer.py", line 664, in get_blob_listing
    maxresults=_MAX_LISTBLOBS_RESULTS)
  File "./blobxfer.py", line 525, in azure_request
    return req(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 485, in list_blobs
    response = self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 132, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 192, in perform_request
    self.send_request_headers(connection, request.headers)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 171, in send_request_headers
    connection.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1157, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

Even tho I can resolve the storage URL on the same server that this is running on. Any help would be great.

**Comment by alfpark** [comment]
Thanks for the issue report. I've identified the issue and will push the fix soon.
