### ISSUE TITLE
TypeError in xrange(maxworkers):

### ISSUE THREAD

**Issue by johnarnold** [Azure/azure-batch-samples#45]
Getting TypeError on the xrange command.   numworkers appears to be set to 64 (default), maybe a problem with assigning maxworkers here?

maxworkers = min([args.numworkers, nstorageops])

Error below...
```
=======================================
      azure blob xfer parameters
=======================================
     subscription id: None
     management cert: None
  transfer direction: local->Azure
      local resource: libfoo.deb
     remote resource: None
  max num of workers: 64
             timeout: None
     storage account: foo
             use SAS: True
 upload as page blob: False
 auto vhd->page blob: False
           container: packages
  blob container URI: https://foo.blob.core.windows.net/packages
    compute file MD5: True
   skip on MD5 match: True
  chunk size (bytes): 4194304
    create container: False
 keep mismatched MD5: False
    recursive if dir: True
 keep root dir on up: False
=======================================

script start time: 2015-09-04 19:50:17
foo.deb md5: ThWXPkbFTO1HAeddfZUv8A==
foo-dev_.deb->foo-dev.deb: local ThWXPkbFTO1HAeddfZUv8A== remote ThWXPkbFTO1HAeddfZUv8A== ->match, skipping upload
performing None put blocks and 0 put block lists
Traceback (most recent call last):
  File "blobxfer.py", line 1406, in <module>
    main()
  File "blobxfer.py", line 1205, in main
    for _ in xrange(maxworkers):
TypeError: an integer is required
Failure occurred communicating with 
```

**Comment by alfpark** [comment]
Can you post your command line? With the SAS/account information obfuscated? Something doesn't appear right since a file localresource is specified, yet it's attempting to upload multiple files.
