### ISSUE TITLE
blobxfer.py error when try to download 0 bytes file

### ISSUE THREAD

**Issue by desmothenes** [Azure/azure-batch-samples#47]
i have some zero byte file in my blob.
when i try to download my blob by 'blobxfer.py',  it show error as below.

```
remote file graph/FER-F.txt length: 0 bytes, md5:
Traceback (most recent call last):
  File "blobxfer.py", line 1404, in <module>
    main()
  File "blobxfer.py", line 1173, in main
    blob, blobdict[blob][0], blobdict[blob][1], False)
  File "blobxfer.py", line 820, in generate_xferspec_download
    filedesc.seek(contentlength - 1)
IOError: [Errno 22] Invalid argument
```

**Comment by alfpark** [comment]
Thanks for reporting this issue and will be addressed soon.
