### ISSUE TITLE
error when '/' in blob

### ISSUE THREAD

**Issue by desmothenes** [Azure/azure-batch-samples#81]
i have some blob name like "https://xxx.blob.core.windows.net/my-container/Top%2024%20P/BV.json"

when i use blobxfer it error like this

```
remote file TOP 20 P/ length: 0 bytes, md5: 1B2M2Y8AsgTpgAmY7PhCfg==
Traceback (most recent call last):
  File "/usr/local/bin/blobxfer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 1245, in main
    blob, blobdict[blob][0], blobdict[blob][1], False)
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 840, in generate_xferspec_download
    lmd5 = compute_md5_for_file_asbase64(localfile)
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 711, in compute_md5_for_file_asbase64
    with open(filename, 'rb') as filedesc:
IsADirectoryError: [Errno 21] Is a directory: '/var/www/html/my-container/TOP 20 P/'
```

**Comment by alfpark** [comment]
It looks like you're attempting to download a blob with a trailing slash. As noted in blobxfer, that isn't a compatible file for your destination OS (looks to be posix-like, Linux?).

Delete the remote virtual directory blob and try again.

**Comment by desmothenes** [comment]
thank you for your advice. now it work.
